name: C-CPP-CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Install cppunit
        run: sudo apt install -y libcppunit-dev
      - name: Configure
        run: ./configure
      - name: Make
        run: make
      - name: Test
        run: make test

